blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/CarlosConcepcion/Hadar-Framework/discussions
    about: Have something you want to ask? Search for or start a new discussion!
